### ISSUE TITLE
Move this logic to a before_action filter

### ISSUE THREAD

**Issue by dummied** [SherSpock/shredit#2]
https://github.com/SherSpock/shredit/pull/1/files#diff-28572c7c3f75b55711adaebe5c9218c1R3

**Comment by dummied** [comment]
Also: https://github.com/SherSpock/shredit/pull/1/files#diff-d5241d488259f32ecbe2f636133e5ddaR3

**Comment by dummied** [comment]
Also: https://github.com/SherSpock/shredit/pull/1/files#diff-28572c7c3f75b55711adaebe5c9218c1R3

**Comment by SherSpock** [comment]
We talked about an acceptable alternative to this that still abstracted out the authentication logic more, and that's what I put in the project
