### ISSUE TITLE
Associated votes with logged in user

### ISSUE THREAD

**Issue by dummied** [SherSpock/shredit#3]
https://github.com/SherSpock/shredit/pull/1/files#diff-5825cb1031a66af39a86288913ac505eR74

**Comment by dummied** [comment]
Also: https://github.com/SherSpock/shredit/pull/1/files#diff-28572c7c3f75b55711adaebe5c9218c1R7

**Comment by SherSpock** [comment]
Solved issue of not passing user_ids to votes created by actions in VotesController and LinksController, closes #3
