### ISSUE TITLE
You might be able to simplify this

### ISSUE THREAD

**Issue by dummied** [SherSpock/shredit#8]
https://github.com/SherSpock/shredit/blob/master/app/views/links/index.html.erb#L2

Try `<%= render @links %>`

**Comment by SherSpock** [comment]
Doesn't work. Open to input

**Comment by dummied** [comment]
Have any more detail there beside "Doesn't work"? An error message or something else?

**Comment by SherSpock** [comment]
Yes there is an error message, but if you don't have immediate ideas I'd rather not do it. My solution works

**Comment by dummied** [comment]
Fair enough. I do wonder what end purpose you have in mind for putting that link partial in application, however.
