### ISSUE TITLE
Only link to create a vote in a user is logged in

### ISSUE THREAD

**Issue by dummied** [SherSpock/shredit#9]
https://github.com/SherSpock/shredit/blob/master/app/views/application/_link.html.erb#L11

**Comment by dummied** [comment]
Also: https://github.com/SherSpock/shredit/blob/master/app/views/application/_link.html.erb#L2

**Comment by SherSpock** [comment]
This is already handled on line four of the LinksController logic

**Comment by dummied** [comment]
That handles making sure the link isn't effective, but the the link is still available to users even if they are unable to vote, creating a bad user experience.

**Comment by SherSpock** [comment]
I disagree. Once I have an up arrow and a down arrow (if I get there), we'll be on the same page
